# Generated by Django 3.0.3 on 2020-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='slug',
            new_name='inspection_tag',
        ),
        migrations.AddField(
            model_name='inspection',
            name='img',
            field=models.ImageField(default=1, upload_to='./'),
            preserve_default=False,
        ),
    ]
