# Generated by Django 3.0.3 on 2020-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20200226_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='img',
            field=models.ImageField(upload_to='./inspection_img'),
        ),
    ]
